spring:
  application:
    name: financial-erp
  datasource:
    url: ${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=SOUTHWND;encrypt=true;trustServerCertificate=true}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    open-in-view: false
    hibernate:
      #ddl-auto: validate
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:SOUTHWND}
  flyway:
    default-schema: ${DB_SCHEMA:SOUTHWND}
    schemas: ${DB_SCHEMA:SOUTHWND}
    create-schemas: true
  thymeleaf:
    cache: false

server:
  error:
    include-message: never
    include-stacktrace: never

security:
  jwt:
    secret: ${JWT_SECRET}
    access-ttl: ${JWT_ACCESS_TTL:PT15M}
    refresh-ttl: ${JWT_REFRESH_TTL:P30D}
  cookie:
    access-name: ${AUTH_ACCESS_COOKIE:erp_access}
    refresh-name: ${AUTH_REFRESH_COOKIE:erp_refresh}
    secure: ${AUTH_COOKIE_SECURE:true}
    same-site: ${AUTH_COOKIE_SAME_SITE:Strict}
    path: ${AUTH_COOKIE_PATH:/}
    domain: ${AUTH_COOKIE_DOMAIN:}
  bootstrap:
    enabled: ${AUTH_BOOTSTRAP_ENABLED:true}
  password:
    salt-length: ${ARGON2_SALT_LENGTH:16}
    hash-length: ${ARGON2_HASH_LENGTH:32}
    parallelism: ${ARGON2_PARALLELISM:1}
    memory: ${ARGON2_MEMORY:65536}
    iterations: ${ARGON2_ITERATIONS:3}